// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	createVillager(ctx context.Context, arg createVillagerParams) (Villager, error)
	getVillager(ctx context.Context, name string) (Villager, error)
	getVillagers(ctx context.Context, limit int32) ([]Villager, error)
}

var _ Querier = (*Queries)(nil)
