// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	createVillager(ctx context.Context, villager string) (Villager, error)
	getVillager(ctx context.Context, villager string) (Villager, error)
}

var _ Querier = (*Queries)(nil)
