// Code generated by sqlc. DO NOT EDIT.
// source: villager.sql

package db

import (
	"context"
)

const createVillager = `-- name: createVillager :one
INSERT INTO villagers (villager) 
VALUES ($1) 
RETURNING id, villager
`

func (q *Queries) createVillager(ctx context.Context, villager string) (Villager, error) {
	row := q.db.QueryRowContext(ctx, createVillager, villager)
	var i Villager
	err := row.Scan(&i.ID, &i.Villager)
	return i, err
}

const getVillager = `-- name: getVillager :one
SELECT id, villager FROM villagers
WHERE villager = $1 
LIMIT 1
`

func (q *Queries) getVillager(ctx context.Context, villager string) (Villager, error) {
	row := q.db.QueryRowContext(ctx, getVillager, villager)
	var i Villager
	err := row.Scan(&i.ID, &i.Villager)
	return i, err
}
